; PlatformIO Project Configuration File

[env:RP2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2350
framework = arduino
build_unflags =  -Os ; disable GCC optimization for size, we want speed
build_flags = 
	-I include ; include directory for header files
	-Ofast ; enable GCC optimization for speed
	-DUSE_TINYUSB ; use TinyUSB stack instead of Arduino's USB stack
board_build.filesystem = littlefs
board_build.filesystem_size = 64k
monitor_speed = 115200
lib_deps = 
	infineon/XENSIV 3D Magnetic Sensor TLx493D@^1.1.2
	adafruit/Adafruit NeoPixel@^1.15.5
	bxparks/AceButton@^1.10.1